application: teach-hub
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: templates/stylesheets

- url: /js
  static_dir: templates/js

- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: templates/images/\1
  upload: templates/images/(.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /fonts/(.*\.ttf)
  static_files: templates/fonts/\1
  upload: templates/fonts/(.*\.ttf)
  mime_type: application/x-font-ttf

- url: /.*
  script: urls.application

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
