application: sci-blog-gr
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: templates/stylesheets

- url: /js
  static_dir: templates/js

- url: /.*
  script: urls.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest